### PR TITLE
Cmake improvements

### PR DESCRIPTION
**Pull request by SkyToGround**
### Description of work

Seeing as it is now being used slightly more it is my intention to update the graylog-logger library a bit. For starters, I have modernised the CMake code. I also had to update the Jenkinsfile due to the requirement of CMake >= 3.9.

I freely admit that I do not fully understand some of the changes I have done to the CMake-code but it appears to be working regardless.

### Issue

Relates to (but does not close) JIRA issue DM-287.

### Acceptance Criteria

Modernised CMake code.

### Unit Tests

N/A

### Other

N/A

---

## Code Review (To be filled in by the reviewer only)

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?

---

## Nominate for Group Code Review (Anyone can nominate it)
Indicate if you think the code should be reviewed in a Thursday code review session.

- [ ] Recommend for group code review

Also, nominate it on the code_review Slack channel.

### CODE REVIEW

**Comment by martukas** [comment]
I can see that this is still a work in progress, but if I may make the following suggestions:
* Please include Ubuntu 18.10 in the Jenkinsfile
* please somehow make Boost optional, or at least use the bincrafters package. I have gone through some pains to excise it in other projects, so I don't want it to haunt me again with conflicting dependencies
* Consider using the modern json library (nlohmann)?

**Comment by SkyToGround** [comment]
@martukas Turns out that I am having some serious build issues that I have to sort out first so I will get back to you on this pull request. I have temporarily removed Ubuntu when sorting out the build issues as it takes a lot of time to build Boost. I will remove Boost but because I am using a bunch of Boost libraries, it will have to wait until I figure out the build issues.

By the way, I am only using Boost in the unit tests.

**Comment by martukas** [comment]
@SkyToGround I totally understood that this is still in a pretty rough stage. No worries.

**Comment by SkyToGround** [comment]
@martukas Looks like it is more or less working now.

**Pull request merged**
